version: '3'
services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT
    volumes:
      -  ./nginx/conf.d:/etc/nginx/conf.d
      - ./../public:/var/www/sf5ld
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
