version: '3'
services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT
    volumes:
      -  ./nginx/conf.d:/etc/nginx/conf.d
      - ./../public:/var/www/sf5ld/public
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
  php_fpm:
    container_name: php_fpm
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT
      - PHP_IDE_CONFIG=serverName=remote
      - XDEBUG_CONFIG=remote_autostart=1
    volumes:
      - ./..:/var/www/sf5ld
  crond:
    container_name: crond
    restart: always
    build:
      context: ./crond
      dockerfile: Dockerfile
    volumes:
      - ./..:/var/www/sf5ld
