name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Build docker-compose
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: WTF
        run: |
          git clone https://github.com/rusinov-artem/sf5ld.git .
          git checkout develop
          ls -la
          cd docker
          docker-compose up -d
          curl localhost/i.php | grep "I'm ok"